queue: filial.4
queue-reply-to: filial.4.reply.to
sucursal-id: 4
server-url: http://localhost:8082
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: franco
    password: franco
    virtual-host: bodega
  multirabbitmq:
    enabled: true
    connections:
      servidor:
        host: localhost
        port: 5672
        username: franco
        password: franco
        virtual-host: bodega