type CuentaBancaria {
    id: ID!,
    persona: Persona,
    banco: Banco,
    moneda: Moneda,
    numero: String,
    tipoCuenta: TipoCuenta,
    creadoEn: Date
    usuario: Usuario
    nombre: String,
    saldo: Float,
    saldoReservado: Float,
    titular: String,
    alias: String,
    activo: Boolean,
    disponibleOperacionesFinancieras: Boolean,
    permiteSaldoNegativo: Boolean
}

input CuentaBancariaInput {
    id:ID
    personaId: Int,
    bancoId: Int,
    monedaId: Int,
    numero: String,
    tipoCuenta: TipoCuenta,
    usuarioId: Int
    nombre: String,
    titular: String,
    alias: String,
    activo: Boolean,
    disponibleOperacionesFinancieras: Boolean,
    permiteSaldoNegativo: Boolean
}

extend type Query {
    cuentaBancaria(id:ID!):CuentaBancaria
    cuentasBancarias(page:Int = 0, size:Int = 10):[CuentaBancaria]!
    countCuentaBancaria: Int
}

extend type Mutation {
    saveCuentaBancaria(cuentaBancaria:CuentaBancariaInput!):CuentaBancaria!
    deleteCuentaBancaria(id:ID!):Boolean!
}

enum TipoCuenta {
    CUENTA_CORRIENTE, CAJA_DE_AHORRO
}

